### ISSUE TITLE
Having trouble running on Windows

### ISSUE THREAD

**Issue by jeremyredhead** [space-elephant/tinyworld-textmode#2]
Hi, this is maybe a PEBKAC/user problem, as I am not so good with the Python,
but I can't manage to install the pyrebase dependency on Windows 10/in a venv

I tried in both ol' CMD.exe, and Git Bash/MinTTY. (I didn't try WSL as I don't use that)

Console log dumps:
- [before installing wheel and upgrading setuptools & pip](https://gist.github.com/jeremyredhead/77015ca639a485f5845d00074c060af9#file-attempt-1-txt)
- [after running `pip install --upgrade pip setuptools wheel`](https://gist.github.com/jeremyredhead/77015ca639a485f5845d00074c060af9#file-attempt-2-txt)

actually, i'm not sure if pip got upgraded or not, it gave a weird error... but I don't think(?) the problem is a too old pip?

---

Any help would be appreciated, I know this is not a very helpful issue, but I'd really like to be able to play T in Y World again,
and the alternative is trying to track down a copy of flash & mucking about with some VM like VirtualBox.

Thanks for making this, I'm glad I'm not the only one who cares about T in Y World :)

**Comment by space-elephant** [comment]
Have you tried `pip3 install pyrebase4` instead? [It seems that the main pyrebase package selects a version of pycryptodome that doesn't work on windows.](https://stackoverflow.com/questions/53461316/pyrebase-install-on-windows-python-3-7-fails) I should probably have a windows VM, but I just assumed it would work because windows is so common.

**Comment by jeremyredhead** [comment]
Thanks, that helped! pyrebase4 installed like a charm!

Unfortunately, that isn't enough to get it running, one must also `pip3 install windows-curses` as Python apparently doesn't natively implement that on Windows.

And in my case (running it from a venv) I had to make sure to run it with `python play.py` as the default launcher/handler `py` interprets shebangs for some reason(!?) which was causing it to escape the venv & run in the normal environment(!!!)

>I just assumed it would work because windows is so common.

Alas, when it comes to anything programming related, there is never any guarantee it works properly on windows. One gets used to the inherent suffering of using windows after a while.
